;;
;; portable lisp editor by Tatsuya Hagino
;;

(in-package :cpl)

;;; Forward declarations
(declaim (ftype (function (t t) t) tvap))
(declaim (ftype (function (t t) t) tvcmd tvp))
(declaim (ftype (function (t) t) tvpp tvpp0 tvpp1 tvpp2 tvpp3 tvpp4 tvpp5))

; an edit structure consists of (tail_list reverse_head_list stack)

; functions which manipulate edit structures

;(defun tvhead (es) (caar es))
(defmacro tvhead (es) `(caar ,es))

;(defun tvend (es) (atom (car es)))
(defmacro tvend (es) `(not (consp (car ,es))))

(defun tvfwd (es)
 (list (cdar es) (cons (caar es) (cadr es)) (caddr es)))

;(defun tvbig (es) (null (cadr es)))
(defmacro tvbig (es) `(null (cadr ,es)))

(defun tvbak (es)
 (list (cons (caadr es) (car es)) (cdadr es) (caddr es)))

;(defun tvtop (es) (null (caddr es)))
(defmacro tvtop (es) `(null (caddr ,es)))

(defun tvdown (es)
 (list (caar es) nil (cons (list (cdar es) (cadr es)) (caddr es))))

(defun tvup (es)
 (prog (tail stack)
	(setq stack (caddr es))
	(setq tail (cons (tvap (car es) (cadr es)) (caar stack)))
	(return (list tail (cadar stack) (cdr stack)))))

(defun tvlast (es)
 (prog (tail head)
	(setq tail (car es))
	(setq head (cadr es))
   aa   (cond ((not (consp tail)) (return (list tail head (caddr es)))))
	(setq head (cons (car tail) head))
	(setq tail (cdr tail))
	(go aa)))

(defun tvap (tail head)
 (cond ((null head) tail)
	(t (tvap (cons (car head) tail) (cdr head)))))

(defun tvdel (es) (cons (cdar es) (cdr es)))

(defun tvins (es s) (list (car es) (cons s (cadr es)) (caddr es)))

(defun tvbot (es) (and (null (car es)) (null (caddr es))))

(defun tvnext (es)
 (cond ((not (tvend es))
	 (cond ((atom (tvhead es)) (tvfwd es))
	       (t (tvdown es))))
	(t (tvfwd (tvup es)))))

(defun tvprev (es)
 (cond ((not (tvbig es))
	 (setq es (tvbak es))
	 (cond ((atom (tvhead es)) es)
	       (t (tvlast (tvdown es)))))
	(t (tvup es))))

(defun tvall (es)
 (cond ((tvtop es) (tvap (car es) (cadr es)))
	(t (tvall (tvup es)))))

; reading routine

(defvar $tvcmd$ nil)

(defun tvread (prompt)
 (prog (x)
	(cond ($tvcmd$ (setq x (car $tvcmd$))
		       (setq $tvcmd$ (cdr $tvcmd$))
		       (return x)))
   aa   (cond ((= (tyipeek) 10) (princ prompt))
	      ((< (tyipeek) 32) (tyi) (go aa)))
	(return (read))))

(defvar $tvfun$ nil)
(defvar $tvcur$ "/\\")
(defvar $tvkill$ nil)
(defvar $tvundo$ nil)
(defvar $tvchg$ nil)
(defvar $tvundop$ t)

(defmacro tv (&rest l)
 (prog (exp es fn cmd kill undo rtn)
	(cond ((null l) (setq fn $tvfun$))
	      (t (setq fn (car l))))
	(cond ((null fn) (error "No previous edit")))
	(setq $tvfun$ fn)
	(setq exp (getd fn))
	(cond ((null exp) (princ "New")
			  (terpri)
			  (setq es (list nil (list fn 'def) nil)))
	      ((atom exp) (error "Wrong type"))
	      (t (setq es (list (list exp) (list fn 'def) nil))))
	(setq kill $tvkill$)
	(setq $tvkill$ nil)
	(setq undo $tvundo$)
	(setq $tvundo$ nil)
	(setq $tvchg$ nil)
	(setq $tvcmd$ nil)
   aa   (setq cmd (tvread ">>"))
	(cond ((eq cmd 'ok)
	       (setq exp (tvall es))
	       (setq $tvfun$ (cadr exp))
	       (putd (cadr exp) (caddr exp))
	       (cond ((eq fn (cadr exp)) (setq rtn fn))
		     (t (setq rtn (list fn 'to (cadr exp)))))
	       (go bb))
	      ((eq cmd 'q) (setq rtn 'quit) (go bb))
	      ((eq cmd '\?)
	       (print '(ok q t f b dr dl ur ul d k y yc s rs undo p pp ppp m e))
	       (terpri)
	       (go aa)))
	(setq es (tvcmd cmd es))
	(go aa)
   bb   (setq $tvkill$ kill)
	(setq $tvundo$ undo)
	(return rtn)))

(defun tverr (es) (progn (tyo 7) (setq $tvcmd$ nil) es))

(defun tvchg (es)
 (cond ((and (null $tvchg$) $tvundop$)
	 (setq $tvundo$ (cons (list es $tvkill$) $tvundo$))
	 (setq $tvchg$ t)
	 es)
	(t es)))

(defun tvcmd (cmd es)
 (cond ((numberp cmd)
	 (prog (cmdl)
	       (setq cmdl (tvread "command-list:"))
	       (cond ((atom cmdl) (return (tverr es))))
	  aa   (cond ((zerop cmd) (return es)))
	       (setq $tvcmd$ (append cmdl $tvcmd$))
	       (setq cmd (1- cmd))
	       (go aa)))
	((and (atom cmd) (get cmd 'tvexe))
	 (apply (get cmd 'tvexe) (list es)))
	((and (atom cmd) (get cmd 'tvcmd))
	 (setq $tvcmd$ (append (get cmd 'tvcmd) $tvcmd$))
	 es)
	(t (tvins (tvchg es) cmd))))

(setf (get 'f 'tvexe) 'tvcmd-f)
(defun tvcmd-f (es) (cond ((not (tvend es)) (tvfwd es)) (t (tverr es))))

(setf (get 'b 'tvexe) 'tvcmd-b)
(defun tvcmd-b (es) (cond ((not (tvbig es)) (tvbak es)) (t (tverr es))))

(setf (get 'dr 'tvexe) 'tvcmd-dr)
(defun tvcmd-dr (es)
 (prog (tes)
	(setq tes es)
   aa   (cond ((tvend tes) (return (tverr es)))
	      ((not (consp (tvhead tes)))
	       (setq tes (tvfwd tes))
	       (go aa)))
	(return (tvdown tes))))

(setf (get 'dl 'tvexe) 'tvcmd-dl)
(defun tvcmd-dl (es)
 (prog (tes)
	(setq tes es)
   aa   (cond ((tvbig tes) (return (tverr es)))
	      ((not (consp (tvhead (setq tes (tvbak tes))))) (go aa)))
	(return (tvlast (tvdown tes)))))

(setf (get 'ur 'tvexe) 'tvcmd-ur)
(defun tvcmd-ur (es) (cond ((tvtop es) (tverr es)) (t (tvfwd (tvup es)))))

(setf (get 'ul 'tvexe) 'tvcmd-ul)
(defun tvcmd-ul (es) (cond ((tvtop es) (tverr es)) (t (tvup es))))

(setf (get 'i 'tvexe) 'tvcmd-i)
(defun tvcmd-i (es) (tvbak (tvins (tvchg es) (tvread "insert:"))))

(setf (get 'd 'tvexe) 'tvcmd-d)
(defun tvcmd-d (es) (cond ((tvend es) (tverr es)) (t (tvdel (tvchg es)))))

(setf (get 'k 'tvexe) 'tvcmd-k)
(defun tvcmd-k (es)
 (cond ((tvend es) (tverr es))
	(t (tvchg es)
	   (setq $tvkill$ (cons (tvhead es) $tvkill$))
	   (tvdel es))))

(setf (get 'y 'tvexe) 'tvcmd-y)
(defun tvcmd-y (es)
 (prog (x)
	(cond ((null $tvkill$) (return (tverr es)))
	      (t (tvchg es)
		 (setq x (car $tvkill$))
		 (setq $tvkill$ (cdr $tvkill$))
		 (return (tvbak (tvins es x)))))))

(setf (get 'yc 'tvexe) 'tvcmd-yc)
(defun tvcmd-yc (es)
 (cond ((null $tvkill$) (tverr es))
	(t (tvchg es)
	   (tvbak (tvins es (car $tvkill$))))))

(setf (get 'undo 'tvexe) 'tvcmd-undo)
(defun tvcmd-undo (es)
 (cond ((null $tvundo$) (tverr es))
	(t (setq es (caar $tvundo$))
	   (setq $tvkill$ (cadar $tvundo$))
	   (setq $tvundo$ (cdr $tvundo$))
	   (setq $tvchg$ nil)
	   es)))

(setf (get 'p 'tvexe) 'tvcmd-p)
(defun tvcmd-p (es)
 (progn (setq $tvchg$ nil)
	 (tvpp (tvp (tvap (cons $tvcur$ (car es)) (cadr es)) 2))
	 (terpri)
	 es))

(setf (get 'pp 'tvexe) 'tvcmd-pp)
(defun tvcmd-pp (es)
 (progn (setq $tvchg$ nil)
	 (tvpp (tvap (cons $tvcur$ (car es)) (cadr es)))
	 (terpri)
	 es))

(setf (get 'ppp 'tvexe) 'tvcmd-ppp)
(defun tvcmd-ppp (es)
 (progn (tvpp (tvall (tvins es $tvcur$)))
	 (terpri)
	 es))

(setf (get 's 'tvexe) 'tvcmd-s)
(defun tvcmd-s (es)
 (prog (x tes)
	(setq x (tvread "Search:"))
	(setq tes es)
   aa   (cond ((tvbot tes) (return (tverr es)))
	      ((and (not (tvend tes)) (equal (tvhead tes) x))
	       (return (tvfwd tes))))
	(setq tes (tvnext tes))
	(go aa)))

(setf (get 'rs 'tvexe) 'tvcmd-rs)
(defun tvcmd-rs (es)
 (prog (x tes)
	(setq x (tvread "Reverse-Search:"))
	(setq tes es)
   aa   (cond ((and (tvtop tes) (tvbig tes)) (return (tverr es))))
	(setq tes (tvprev tes))
	(cond ((and (not (tvend tes)) (equal (tvhead tes) x))
	       (return tes)))
	(go aa)))

(setf (get 't 'tvexe) 'tvcmd-t)
(defun tvcmd-t (es)
 (prog ()
   aa   (cond ((tvtop es) (return es)))
	(setq es (tvup es))
	(go aa)))

(setf (get 'm 'tvexe) 'tvcmd-m)
(defun tvcmd-m (es)
 (prog (nm cmdl)
	(setq nm (tvread "macro-name:"))
	(cond ((or (null nm) (not (atom nm))) (return (tverr es))))
	(setq cmdl (tvread "macro-body-list:"))
	(cond ((null cmdl) (remf (symbol-plist nm) 'tvcmd) (return es))
	      ((atom cmdl) (return (tverr es))))
	(setf (get nm 'tvcmd) cmdl)
	(return es)))

(setf (get 'e 'tvexe) 'tvcmd-e)
(defun tvcmd-e (es)
 (prog (x)
	(setq x (tvread "evaluate:"))
	(setq x (errset (eval x)))
	(cond ((not (atom x)) (print (car x)) (terpri))
	      (t (return (tverr es))))
	       (return es)))

(defun tvp (fml dp)
 (cond ((atom fml) fml)
	((zerop dp) '|&|)
	(t (cons (tvp (car fml) (1- dp)) (tvp (cdr fml) dp)))))

(defun tvpp (fml) (tvpp0 fml 0 (charcnt nil)))

; We should use (flatsize l max) instead of (flatc l max),
; but the latter is much faster.

(defun tvpp0 (l lmar rmar)
 (cond ((and (>= lmar 50) (> (flatc l 101) 100))
	 (terpri)
	 (princ "; <<<<< start back on the left <<<<<")
	 (terpri)
	 (tvpp0 l 5 rmar)
	 (terpri)
	 (princ "; >>>>> continue on the right >>>>>")
	 (terpri))
	(t (tab lmar)
	   (cond ((or (not (consp l))
		      (and (atom (car l)) (atom (cdr l))))
		  (tvpp1 l))
		 ((< (+ lmar (flatc l (- rmar lmar))) rmar) (tvpp1 l))
		 ((and (not (and (eq (car l) 'def) (tvpp2 l lmar rmar)))
		       (not (and (memq (car l) '(lambda nlambda lexpr macro))
				 (tvpp3 l lmar rmar)))
		       (not (and (eq (car l) 'quote) (tvpp5 l lmar rmar)))
		       (not (and (eq (car l) 'prog) (tvpp4 l lmar rmar))))
		  (prog (c)
			(princ '|(|)
			(setq lmar (1+ lmar))
			(tvpp0 (car l) lmar rmar)
			(cond ((null (cdr l)) (princ '|)|) (return nil))
			      ((atom (car l)) (princ '| |)
					      (setq lmar (nwritn nil)))
			      (t (terpri)))
		   aa   (setq l (cdr l))
			(cond ((atom l) (princ '|. |)
					(tvpp0 l (+ lmar 2) rmar)
					(princ '|)|)
					(return nil)))
			(tvpp0 (car l) lmar rmar)
			(cond ((null (cdr l)) (princ '|)|) (return nil)))
			(go aa)))))))

(defun tvpp1 (l)
 (cond ((eq l $tvcur$) (princ l))
	((atom l) (print l))
	((and (eq (car l) 'quote)
	      (not (atom (cdr l)))
	      (null (cddr l)))
	 (princ '|'|)
	 (tvpp1 (cadr l)))
	(t (princ '|(|)
	   (prog ()
	    aa   (tvpp1 (car l))
		 (setq l (cdr l))
		 (cond ((null l) (princ '|)|) (return nil))
		       ((atom l) (princ '| . |)
				 (tvpp1 l)
				 (princ '|)|)
				 (return nil)))
		 (princ '| |)
		 (go aa)))))

(defun tvpp2 (l lmar rmar)
 (cond ((and (zerop lmar)
	      (cadr l)
	      (atom (cadr l))
	      (consp (caddr l))
	      (null (cdddr l)))
	 (princ '|(def |)
	 (tvpp1 (cadr l))
	 (terpri)
	 (tvpp0 (caddr l) 2 rmar)
	 (princ '|)|)
	 t)
	(t nil)))

(defun tvpp3 (l lmar rmar)
 (cond ((and (not (atom (cdr l)))
	      (not (atom (cddr l)))
	      (null (cdddr l)))
	 (princ '|(|)
	 (princ (car l))
	 (princ '| |)
	 (tvpp0 (cadr l) (nwritn nil) rmar)
	 (terpri)
	 (tvpp0 (caddr l) (+ lmar 2) rmar)
	 (princ '|)|)
	 t)
	(t nil)))

(defun tvpp4 (l lmar rmar)
 (prog (c)
	(cond ((or (atom (cdr l))
		   (atom (cddr l))
		   (atom (cdddr l)))
	       (return nil)))
        (princ '|(prog |)
	(tvpp0 (cadr l) (+ lmar 6) rmar)
	(setq l (cddr l))
   aa   (cond ((null l) (princ '|)|) (return t)))
	(terpri)
	(cond ((not (atom (car l))) (go bb)))
        (tab (1+ lmar))
   cc   (tvpp1 (car l))
	(princ '| |)
	(setq l (cdr l))
	(cond ((null l) (tab (+ lmar 6)) (go aa))
	((atom (car l)) (go cc)))
   bb   (tvpp0 (car l) (+ lmar 6) rmar)
	(setq l (cdr l))
	(go aa)))

(defun tvpp5 (l lmar rmar)
 (cond ((and (not (atom (cdr l))) (null (cddr l)))
	 (princ '|'|)
	 (tvpp0 (cadr l) (1+ lmar) rmar)
	 t)
	(t nil)))

(progn (princ "TV lisp (version 1.1 SBCL) January 2026") (terpri))
